services:
  backend:
    image: ikang-backend
    build:
      context: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - database
  database:
    image: postgres:alpine
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
