services:
  # app:
  #   container_name: "ikang-backend"
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=.env
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   command: bun start
  #   depends_on:
  #     - database
  database:
    container_name: "ikang-db"
    image: ${POSTGRES_IMAGE}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-init/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql

volumes:
  postgres-data:
