export const habitats = [
  {
    name: "Coral Reef",
    slug: "coral-reef",
  },
  {
    name: "Freshwater Lake",
    slug: "freshwater-lake",
  },
  {
    name: "Deep Ocean",
    slug: "deep-ocean",
  },
  {
    name: "Mangrove Forest",
    slug: "mangrove-forest",
  },
  {
    name: "Kelp Forest",
    slug: "kelp-forest",
  },
  {
    name: "Estuary",
    slug: "estuary",
  },
  {
    name: "Rocky Shore",
    slug: "rocky-shore",
  },
  {
    name: "Open Ocean",
    slug: "open-ocean",
  },
  {
    name: "River",
    slug: "river",
  },
  {
    name: "Swamp",
    slug: "swamp",
  },
];

export const predators = [
  {
    name: "Great White Shark",
    slug: "great-white-shark",
  },
  {
    name: "Killer Whale",
    slug: "killer-whale",
  },
  {
    name: "Barracuda",
    slug: "barracuda",
  },
  {
    name: "Lionfish",
    slug: "lionfish",
  },
  {
    name: "Moray Eel",
    slug: "moray-eel",
  },
  {
    name: "Piranha",
    slug: "piranha",
  },
  {
    name: "Tiger Shark",
    slug: "tiger-shark",
  },
  {
    name: "Giant Squid",
    slug: "giant-squid",
  },
  {
    name: "Saltwater Crocodile",
    slug: "saltwater-crocodile",
  },
  {
    name: "Bluefin Tuna",
    slug: "bluefin-tuna",
  },
];

export const fishes = [
  {
    slug: "clownfish",
    name: "Clownfish",
    scientificName: "Amphiprion ocellaris",
    size: "10 cm",
    diet: "Omnivore",
    lifespan: "6 years",
    status: "Least Concern",
    color: "Orange",
    waterType: "Saltwater",
    reproduction: "Egg-layer",
    behavior: "Peaceful",
    habitatSlugs: ["coral-reef"],
    predatorSlugs: ["lionfish"],
  },
  {
    slug: "betta",
    name: "Betta",
    scientificName: "Betta splendens",
    size: "7 cm",
    diet: "Carnivore",
    lifespan: "3 years",
    status: "Vulnerable",
    color: "Blue",
    waterType: "Freshwater",
    reproduction: "Bubble Nest Builder",
    behavior: "Aggressive",
  },
  {
    slug: "goldfish",
    name: "Goldfish",
    scientificName: "Carassius auratus",
    size: "20 cm",
    diet: "Omnivore",
    lifespan: "10 years",
    status: "Least Concern",
    color: "Gold",
    waterType: "Freshwater",
    reproduction: "Egg-layer",
    behavior: "Peaceful",
  },
  {
    slug: "angelfish",
    name: "Angelfish",
    scientificName: "Pterophyllum scalare",
    size: "15 cm",
    diet: "Omnivore",
    lifespan: "8 years",
    status: "Least Concern",
    color: "Silver",
    waterType: "Freshwater",
    reproduction: "Egg-layer",
    behavior: "Semi-aggressive",
  },
  {
    slug: "blue-tang",
    name: "Blue Tang",
    scientificName: "Paracanthurus hepatus",
    size: "30 cm",
    diet: "Herbivore",
    lifespan: "12 years",
    status: "Least Concern",
    color: "Blue",
    waterType: "Saltwater",
    reproduction: "Egg-layer",
    behavior: "Peaceful",
  },
  {
    slug: "neon-tetra",
    name: "Neon Tetra",
    scientificName: "Paracheirodon innesi",
    size: "4 cm",
    diet: "Omnivore",
    lifespan: "5 years",
    status: "Least Concern",
    color: "Blue and Red",
    waterType: "Freshwater",
    reproduction: "Egg-layer",
    behavior: "Peaceful",
  },
  {
    slug: "discus",
    name: "Discus",
    scientificName: "Symphysodon spp.",
    size: "20 cm",
    diet: "Omnivore",
    lifespan: "10 years",
    status: "Least Concern",
    color: "Red and Blue",
    waterType: "Freshwater",
    reproduction: "Egg-layer",
    behavior: "Peaceful",
  },
  {
    slug: "lionfish",
    name: "Lionfish",
    scientificName: "Pterois volitans",
    size: "38 cm",
    diet: "Carnivore",
    lifespan: "15 years",
    status: "Least Concern",
    color: "Red and White",
    waterType: "Saltwater",
    reproduction: "Egg-layer",
    behavior: "Aggressive",
  },
  {
    slug: "guppy",
    name: "Guppy",
    scientificName: "Poecilia reticulata",
    size: "6 cm",
    diet: "Omnivore",
    lifespan: "2 years",
    status: "Least Concern",
    color: "Multicolor",
    waterType: "Freshwater",
    reproduction: "Live-bearer",
    behavior: "Peaceful",
  },
  {
    slug: "oscar",
    name: "Oscar",
    scientificName: "Astronotus ocellatus",
    size: "35 cm",
    diet: "Carnivore",
    lifespan: "10 years",
    status: "Least Concern",
    color: "Black and Orange",
    waterType: "Freshwater",
    reproduction: "Egg-layer",
    behavior: "Semi-aggressive",
  },
];
