import { ulid } from "ulid";

export const fishes = [
  {
    id: ulid(),
    name: "Clownfish",
    scientificName: "Amphiprion ocellaris",
    size: "10 cm",
    diet: "Omnivore",
    lifespan: "6 years",
    status: "Least Concern",
    color: "Orange",
    waterType: "Saltwater",
    reproduction: "Egg-layer",
    behavior: "Peaceful",
  },
  {
    id: ulid(),
    name: "Betta",
    scientificName: "Betta splendens",
    size: "7 cm",
    diet: "Carnivore",
    lifespan: "3 years",
    status: "Vulnerable",
    color: "Blue",
    waterType: "Freshwater",
    reproduction: "Bubble Nest Builder",
    behavior: "Aggressive",
  },
  {
    id: ulid(),
    name: "Goldfish",
    scientificName: "Carassius auratus",
    size: "20 cm",
    diet: "Omnivore",
    lifespan: "10 years",
    status: "Least Concern",
    color: "Gold",
    waterType: "Freshwater",
    reproduction: "Egg-layer",
    behavior: "Peaceful",
  },
  {
    id: ulid(),
    name: "Angelfish",
    scientificName: "Pterophyllum scalare",
    size: "15 cm",
    diet: "Omnivore",
    lifespan: "8 years",
    status: "Least Concern",
    color: "Silver",
    waterType: "Freshwater",
    reproduction: "Egg-layer",
    behavior: "Semi-aggressive",
  },
  {
    id: ulid(),
    name: "Blue Tang",
    scientificName: "Paracanthurus hepatus",
    size: "30 cm",
    diet: "Herbivore",
    lifespan: "12 years",
    status: "Least Concern",
    color: "Blue",
    waterType: "Saltwater",
    reproduction: "Egg-layer",
    behavior: "Peaceful",
  },
  {
    id: ulid(),
    name: "Neon Tetra",
    scientificName: "Paracheirodon innesi",
    size: "4 cm",
    diet: "Omnivore",
    lifespan: "5 years",
    status: "Least Concern",
    color: "Blue and Red",
    waterType: "Freshwater",
    reproduction: "Egg-layer",
    behavior: "Peaceful",
  },
  {
    id: ulid(),
    name: "Discus",
    scientificName: "Symphysodon spp.",
    size: "20 cm",
    diet: "Omnivore",
    lifespan: "10 years",
    status: "Least Concern",
    color: "Red and Blue",
    waterType: "Freshwater",
    reproduction: "Egg-layer",
    behavior: "Peaceful",
  },
  {
    id: ulid(),
    name: "Lionfish",
    scientificName: "Pterois volitans",
    size: "38 cm",
    diet: "Carnivore",
    lifespan: "15 years",
    status: "Least Concern",
    color: "Red and White",
    waterType: "Saltwater",
    reproduction: "Egg-layer",
    behavior: "Aggressive",
  },
  {
    id: ulid(),
    name: "Guppy",
    scientificName: "Poecilia reticulata",
    size: "6 cm",
    diet: "Omnivore",
    lifespan: "2 years",
    status: "Least Concern",
    color: "Multicolor",
    waterType: "Freshwater",
    reproduction: "Live-bearer",
    behavior: "Peaceful",
  },
  {
    id: ulid(),
    name: "Oscar",
    scientificName: "Astronotus ocellatus",
    size: "35 cm",
    diet: "Carnivore",
    lifespan: "10 years",
    status: "Least Concern",
    color: "Black and Orange",
    waterType: "Freshwater",
    reproduction: "Egg-layer",
    behavior: "Semi-aggressive",
  },
];

export const habitats = [
  {
    id: ulid(),
    name: "Coral Reef",
  },
  {
    id: ulid(),
    name: "Freshwater Lake",
  },
  {
    id: ulid(),
    name: "Deep Ocean",
  },
  {
    id: ulid(),
    name: "Mangrove Forest",
  },
  {
    id: ulid(),
    name: "Kelp Forest",
  },
  {
    id: ulid(),
    name: "Estuary",
  },
  {
    id: ulid(),
    name: "Rocky Shore",
  },
  {
    id: ulid(),
    name: "Open Ocean",
  },
  {
    id: ulid(),
    name: "River",
  },
  {
    id: ulid(),
    name: "Swamp",
  },
];

export const predators = [
  {
    id: ulid(),
    name: "Great White Shark",
  },
  {
    id: ulid(),
    name: "Killer Whale",
  },
  {
    id: ulid(),
    name: "Barracuda",
  },
  {
    id: ulid(),
    name: "Lionfish",
  },
  {
    id: ulid(),
    name: "Moray Eel",
  },
  {
    id: ulid(),
    name: "Piranha",
  },
  {
    id: ulid(),
    name: "Tiger Shark",
  },
  {
    id: ulid(),
    name: "Giant Squid",
  },
  {
    id: ulid(),
    name: "Saltwater Crocodile",
  },
  {
    id: ulid(),
    name: "Bluefin Tuna",
  },
];
